name: CI Pipeline - API + Worker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  api-ci:
    name: API - Build, Test & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API
        run: docker build -t api-test ./api

      - name: Test API
        run: docker run --rm api-test npm test || echo "No tests found"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push API Image
        run: |
          docker tag api-test ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:latest


  worker-ci:
    name: Worker - Build, Test & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Worker
        run: docker build -t worker-test ./worker

      - name: Test Worker
        run: docker run --rm worker-test npm test || echo "No tests found"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Worker Image
        run: |
          docker tag worker-test ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest
